FROM node:20.11.1

WORKDIR /gitsync
COPY . .

WORKDIR /gitsync/web/frontend
RUN npm install
RUN npm run build

WORKDIR /gitsync/web/backend
RUN npm install express 
RUN npm install path 
RUN npm install fs 
RUN npm install child_process
RUN npm install body-parser 

CMD ["node", "index.js"]