version: '3.8'

services:
  web:
    image: gitsync_web
    container_name: web
    restart: always
    ports:
      - "9002:9002"
    volumes:
      - ./data:/gitsync/data
      - /:/gitsync_user_systeme_data