  version: '3.8'

services:
  web:
    image: node:20.11.1
    container_name: web
    ports:
      - "7000:7000"
    volumes:
      - ./web:/web
      - ./data:/data  # Montage du dossier data pour stocker les fichiers JSON
    command: cd ../frontend && npm install && cd web/backend && npm install && npm start
