FROM ubuntu:22.04

WORKDIR /gitsync
COPY ./scripts /gitsync/scripts

RUN apt update -y
RUN apt upgrade -y

RUN apt install python3 -y
RUN apt install pip -y
RUN apt install git -y

RUN pip3 install -r /gitsync/scripts/requirements.txt

CMD ["python3", "/gitsync/scripts/gitsync.py"]