version: '3.8'

services:
  web:
    image: node:20.11.1
    container_name: web
    ports:
      - "9002:7000"
    volumes:
      - ./:/gitsync 
    command: sh -c "cd /gitsync/web/frontend && npm install && npm run build && cd /gitsync/web/backend && npm install && npm start"

  gitsync:
    image: python:3.11
    container_name: gitsync
    volumes:
      - ./:/gitsync
      - /:/user_sys
    command: sh -c "cd /gitsync && python3 gitsync.py"