version: '3.8'

services:
  web:
    image: node:20.11.1
    container_name: web
    ports:
      - "9002:7000"
    volumes:
      - ./:/gitsync 
    command: sh -c "cd /gitsync/web/frontend && npm install && cd /gitsync/web/backend && npm install && npm start"

  gitsync:
    image: ubuntu:22.04
    container_name: gitsync
    volumes:
      - ./:/gitsync
      - /:/user_sys
    command: sh -c "cd /gitsync/scripts && chmod +x ubuntu_setup.sh && ./ubuntu_setup.sh"